"""Tech-job filter: classifies a JobListing as tech-related or not."""

from job_search_agent.collectors.base import JobListing

# Substrings checked against the lowercased job title.
_TECH_TITLE_KEYWORDS: frozenset[str] = frozenset({
    "engineer",
    "developer",
    "programmer",
    "architect",
    "devops",
    "sre",
    "platform",
    "machine learning",
    "software",
    "backend",
    "front-end",
    "frontend",
    "full-stack",
    "fullstack",
    "cloud",
    "infrastructure",
    "cybersecurity",
    "data scientist",
    "data analyst",
    "data engineer",
    "analytics engineer",
    "ml engineer",
    "ai engineer",
    "security engineer",
    "qa engineer",
    "test engineer",
    "mobile developer",
    "ios developer",
    "android developer",
    "web developer",
    "site reliability",
    "database administrator",
    "systems administrator",
    "network engineer",
    "it specialist",
    "it engineer",
    "technical lead",
    "tech lead",
})

# Exact lowercase tags that indicate a tech role.
_TECH_TAG_KEYWORDS: frozenset[str] = frozenset({
    "python",
    "javascript",
    "typescript",
    "java",
    "go",
    "golang",
    "rust",
    "c++",
    "c#",
    "ruby",
    "php",
    "scala",
    "swift",
    "kotlin",
    "sql",
    "nosql",
    "react",
    "angular",
    "vue",
    "node",
    "nodejs",
    "docker",
    "kubernetes",
    "aws",
    "gcp",
    "azure",
    "terraform",
    "git",
    "linux",
    "unix",
    "hadoop",
    "spark",
    "tensorflow",
    "pytorch",
    "machine learning",
    "deep learning",
    "backend",
    "frontend",
    "devops",
    "sre",
    "engineering",
    "software",
    "data science",
    "analytics",
    "cloud",
    "api",
    "microservices",
    "infrastructure",
    "cybersecurity",
    "mobile",
    "ios",
    "android",
    "web development",
    "data engineering",
    "mlops",
    "llm",
    "ai",
})


def is_tech_job(job: JobListing) -> bool:
    """Return True if *job* is a tech role based on its title and tags."""
    title_lower = job["title"].lower()
    if any(kw in title_lower for kw in _TECH_TITLE_KEYWORDS):
        return True
    tags_lower = {t.lower() for t in job["tags"]}
    return bool(tags_lower & _TECH_TAG_KEYWORDS)
